[package]
name = "mini-redis"
version = "0.1.0"
authors = ["Rohan Mishra <rohanmishra2017@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "1"
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"

